<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>demo Customers App</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="<?php echo WEBROOT;?>css/styles.css" rel="stylesheet" type="text/css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</head>
<body>
<?php echo $body; ?>
</body>
</html>
